### ISSUE TITLE
V2 REWRITE

### ISSUE THREAD

**Issue by THEGOLDENPRO** [THEGOLDENPRO/aghpb-cli#2]
WIP, not set in stone

## TODO
- [ ] Add Fzf as an optional but recommended selector.
- [ ] Show image in the terminal using chafa and the kitty protocol.
- [ ] Key functions
  - [ ] `ENTER` --> Display a random aghpb image.
  - [ ] `LEFT ARROW` --> Return to the previews viewed image.
  - [ ] `M` --> Show metadata of the image.
  - [ ] `R` --> Display / refresh the image.
